name: Deploy Website

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: arn:aws:iam::730335616323:role/GitHubActionsDeploymentRole
      #     aws-region: us-east-1
      - name: Setup Node.js from .nvmrc
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run Astro Check
        run: npx astro check
      - name: Build application
        run: npm run build
      # - name: Deploy to S3
      #   run: aws s3 sync --delete ./dist/ s3://${{ secrets.BUCKET_ID }}
      # - name: Create CloudFront invalidation
      #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
